apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app.kubernetes.io/instance: comfyui
    app.kubernetes.io/name: comfyui
    workload.user.cattle.io/workloadselector: apps.deployment-llm-comfyui
  name: comfyui
  namespace: llm
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-llm-comfyui
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: comfyui
        app.kubernetes.io/name: comfyui
        workload.user.cattle.io/workloadselector: apps.deployment-llm-comfyui
      name: comfyui
      namespace: llm
    spec:
      containers:
      - env:
        - name: HIP_VISIBLE_DEVICES
          value: "1"
        - name: COMMANDLINE_ARGS
          value: --listen
        - name: HSA_OVERRIDE_GFX_VERSION
          value: 10.3.0
        - name: TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL
          value: "0"
        - name: PYTORCH_TUNABLEOP_ENABLED
          value: "0"
        - name: PYTORCH_ROCM_ARCH
          value: "gfx1030"
        image: moophlo/comfyui
        imagePullPolicy: Always
        name: comfyui
        ports:
        - containerPort: 8188
          name: 8188tcp
          protocol: TCP
        resources:
          limits:
            amd.com/gpu: "1"
        securityContext:
          capabilities:
            add:
            - SYS_PTRACE
          privileged: true
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /dockerx/ComfyUI/models
          name: comfyui-models
        - mountPath: /dockerx/ComfyUI/custom_nodes
          name: comfyui-custom-nodes
      dnsConfig:
        nameservers:
        - 1.1.1.1
      dnsPolicy: None
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: gpu
        operator: Equal
        value: "true"
      volumes:
      - name: comfyui-models
        persistentVolumeClaim:
          claimName: comfyui-models
      - name: comfyui-custom-nodes
        persistentVolumeClaim:
          claimName: comfyui-custom-nodes
