apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app.kubernetes.io/instance: comfyui
    app.kubernetes.io/name: comfyui
    workload.user.cattle.io/workloadselector: apps.deployment-llm-comfyui
  name: comfyui
  namespace: llm
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-llm-comfyui
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: comfyui
        app.kubernetes.io/name: comfyui
        workload.user.cattle.io/workloadselector: apps.deployment-llm-comfyui
      name: comfyui
      namespace: llm
    spec:
      containers:
      - env:
        - name: HIP_VISIBLE_DEVICES
          value: '1'
        - name: COMMANDLINE_ARGS
          value: '--listen --use-split-cross-attention --force-fp32'
        - name: HSA_OVERRIDE_GFX_VERSION
          value: 10.3.0
        - name: TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL
          value: "0"
        - name: PYTORCH_TUNABLEOP_ENABLED
          value: "0"
        - name: PYTORCH_ROCM_ARCH
          value: "gfx1030"
        - name: PYTORCH_HIP_ALLOC_CONF
          value: >-
            garbage_collection_threshold:0.6,max_split_size_mb:256,expandable_segments:True
        image: moophlo/comfyui
        imagePullPolicy: Always
        name: comfyui
        ports:
        - containerPort: 8188
          name: 8188tcp
          protocol: TCP
        resources:
          limits:
            amd.com/gpu: "1"
        securityContext:
          capabilities:
            add:
            - SYS_PTRACE
          privileged: true
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /dockerx/ComfyUI/models
          name: comfyui-models
        - mountPath: /dockerx/ComfyUI/output
          name: comfyui-output
        - mountPath: /dockerx/ComfyUI/user/default/workflows
          name: comfyui-workflows
        - mountPath: /dockerx/ComfyUI/custom_nodes
          name: comfyui-custom-nodes
        - name: login
          mountPath: /dockerx/ComfyUI/login
      dnsConfig:
        nameservers:
        - 1.1.1.1
      dnsPolicy: None
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: gpu
        operator: Equal
        value: "true"
      volumes:
      - name: comfyui-models
        persistentVolumeClaim:
          claimName: comfyui-models
      - name: comfyui-output
        persistentVolumeClaim:
          claimName: comfyui-output
      - name: comfyui-workflows
        persistentVolumeClaim:
          claimName: comfyui-workflows
      - name: comfyui-custom-nodes
        persistentVolumeClaim:
          claimName: comfyui-custom-nodes
      - name: login
        persistentVolumeClaim:
          claimName: comfyui-login
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-models
  namespace: llm
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: manual
  volumeMode: Filesystem
  volumeName: comfyui-models
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-custom-nodes
  namespace: llm
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
  volumeMode: Filesystem
  volumeName: comfyui-custom-nodes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-output
  namespace: llm
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: manual
  volumeMode: Filesystem
  volumeName: comfyui-output
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-workflows
  namespace: llm
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  volumeMode: Filesystem
  volumeName: comfyui-workflows
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-login
  namespace: llm
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  volumeMode: Filesystem
  volumeName: comfyui-login
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: comfyui-models
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 500Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: comfyui-models
    namespace: llm
  hostPath:
    path: /media/muflo/Volume10TB/AI/kube-comfyui-models
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: comfyui-custom-nodes
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: comfyui-custom-nodes
    namespace: llm
  hostPath:
    path: /media/muflo/Volume10TB/AI/kube-comfyui-custom-nodes
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: comfyui-output
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: comfyui-output
    namespace: llm
  hostPath:
    path: /media/muflo/Volume10TB/AI/kube-comfyui-output
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: comfyui-workflows
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: comfyui-workflows
    namespace: llm
  hostPath:
    path: /media/muflo/Volume10TB/AI/kube-comfyui-workflows
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: comfyui-login
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: comfyui-login
    namespace: llm
  hostPath:
    path: /media/muflo/Volume10TB/AI/kube-comfyui-login
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem
