apiVersion: v1
kind: PersistentVolume
metadata:
  name: comfyui-custom-nodes
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: comfyui-custom-nodes
    namespace: llm
  hostPath:
    path: /media/muflo/Volume10TB/AI/kube-comfyui-custom-nodes
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem

