apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-models
  namespace: llm
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: manual
  volumeMode: Filesystem
  volumeName: comfyui-models
