apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-custom-nodes
  namespace: llm
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
  volumeMode: Filesystem
  volumeName: comfyui-custom-nodes
