# runnerdeployment.yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: comfyui-runnerdeploy
  namespace: github-actions
spec:
  replicas: 1
  template:
    spec:
      repository: moophlo/ComfyUI
